development:
  password: $THEMEKIT_PASSWORD
  theme_id: $THEMEKIT_THEME_ID
  store: $THEMEKIT_STORE
production:
  password: $THEMEKIT_PASSWORD
  theme_id: $THEMEKIT_THEME_ID
  store: $THEMEKIT_STORE
  readonly: true
